# Generated by Django 4.2.16 on 2024-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
