version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres  # postgres용 Dockerfile
    container_name: backend
    environment:
      POSTGRES_DB: ssafyrag
      POSTGRES_USER: ssafyuser
      POSTGRES_PASSWORD: 1234
    working_dir: /home
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/home/app
    ports:
      - "5430:5433"
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    # restart: unless-stopped

  vue:
    build:
      context: .
      dockerfile: Dockerfile.vue  # vue용 Dockerfile
    container_name: frontend
    network_mode: host
    working_dir: /app
    volumes:
      - .:/app  # 로컬 디렉토리를 컨테이너에 마운트
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  postgres_data: