# 베이스 이미지 선택
FROM kwon0528/postgres_backend:0.3

# 필요한 패키지 설치 (bash 설치)
RUN apt-get update && apt-get install -y bash

# 작업 디렉토리 설정
WORKDIR /root

# back.sh 파일 복사
COPY back.sh /root/back.sh

# 실행 권한 부여
RUN chmod +x /root/back.sh

# 실행
CMD sh /root/back.sh