version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    working_dir: /app
    environment:
      POSTGRES_DB: ssafyrag
      POSTGRES_USER: ssafyuser
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: unless-stopped

  vue:
    image: ubuntu
    container_name: vue
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    depends_on:
      - postgres

volumes:
  postgres_data:
